plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'chursov'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    lombokVersion = '1.18.38'
    allureVersion = '2.29.1'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'io.rest-assured:rest-assured:5.5.5'
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testImplementation "io.qameta.allure:allure-junit5:${allureVersion}"
    testImplementation "io.qameta.allure:allure-rest-assured:${allureVersion}"
    testImplementation 'org.aeonbits.owner:owner:1.0.12'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.19.0'
    testImplementation 'org.assertj:assertj-core:3.27.3'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
}